# Generated by Django 5.2.7 on 2026-01-17 11:07

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_google_calendar_id_task_google_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=16)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=core.models.invite_expiry_default)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.household')),
            ],
        ),
    ]
