# Generated by Django 5.2.7 on 2026-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=16),
        ),
    ]
