# Generated by Django 5.2.7 on 2026-01-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('password', 'Password'), ('google', 'Google')], default='password', max_length=20),
        ),
    ]
